// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type BuildingRooms struct {
	Building string  `json:"building" bson:"building"`
	Rooms    []*Room `json:"rooms,omitempty" bson:"rooms"`
	Lat      float64 `json:"lat" bson:"lat"`
	Lon      float64 `json:"lon" bson:"lon"`
}

type CollectionRequirement struct {
	Type     string `json:"type"`
	Name     string `json:"name"`
	Required int32  `json:"required"`
	Options  any    `json:"options,omitempty"`
}

type Course struct {
	ID                     string                 `json:"_id"`
	SubjectPrefix          string                 `json:"subject_prefix"`
	CourseNumber           string                 `json:"course_number"`
	Title                  string                 `json:"title"`
	Description            string                 `json:"description"`
	EnrollmentReqs         string                 `json:"enrollment_reqs"`
	School                 string                 `json:"school"`
	CreditHours            string                 `json:"credit_hours"`
	ClassLevel             string                 `json:"class_level"`
	ActivityType           string                 `json:"activity_type"`
	Grading                string                 `json:"grading"`
	InternalCourseNumber   string                 `json:"internal_course_number"`
	Prerequisites          *CollectionRequirement `json:"prerequisites,omitempty"`
	Corequisites           *CollectionRequirement `json:"corequisites,omitempty"`
	CoOrPreRequisites      *CollectionRequirement `json:"co_or_pre_requisites,omitempty"`
	Sections               []string               `json:"sections"`
	LectureContactHours    string                 `json:"lecture_contact_hours"`
	LaboratoryContactHours string                 `json:"laboratory_contact_hours"`
	OfferingFrequency      string                 `json:"offering_frequency"`
	CatalogYear            string                 `json:"catalog_year"`
	Attributes             any                    `json:"attributes,omitempty"`
}

type CourseFilter struct {
	SubjectPrefix          *string `json:"subject_prefix,omitempty" bson:"subject_prefix,omitempty"`
	CourseNumber           *string `json:"course_number,omitempty" bson:"course_number,omitempty"`
	School                 *string `json:"school,omitempty" bson:"school,omitempty"`
	CreditHours            *string `json:"credit_hours,omitempty" bson:"credit_hours,omitempty"`
	ClassLevel             *string `json:"class_level,omitempty" bson:"class_level,omitempty"`
	ActivityType           *string `json:"activity_type,omitempty" bson:"activity_type,omitempty"`
	Grading                *string `json:"grading,omitempty" bson:"grading,omitempty"`
	InternalCourseNumber   *string `json:"internal_course_number,omitempty" bson:"internal_course_number,omitempty"`
	LectureContactHours    *string `json:"lecture_contact_hours,omitempty" bson:"lecture_contact_hours,omitempty"`
	LaboratoryContactHours *string `json:"laboratory_contact_hours,omitempty" bson:"laboratory_contact_hours,omitempty"`
	OfferingFrequency      *string `json:"offering_frequency,omitempty" bson:"offering_frequency,omitempty"`
	CatalogYear            *string `json:"catalog_year,omitempty" bson:"catalog_year,omitempty"`
}

type Event struct {
	ID                 string    `json:"_id" bson:"_id"`
	Summary            string    `json:"summary" bson:"summary"`
	Location           string    `json:"location" bson:"location"`
	StartTime          time.Time `json:"start_time" bson:"start_time"`
	EndTime            time.Time `json:"end_time" bson:"end_time"`
	Description        string    `json:"description" bson:"description"`
	EventType          []string  `json:"event_type" bson:"event_type"`
	TargetAudience     []string  `json:"target_audience" bson:"target_audience"`
	Topic              []string  `json:"topic" bson:"topic"`
	EventTags          []string  `json:"event_tags" bson:"event_tags"`
	EventWebsite       string    `json:"event_website" bson:"event_website"`
	Department         []string  `json:"department" bson:"department"`
	ContactName        string    `json:"contact_name" bson:"contact_name"`
	ContactEmail       string    `json:"contact_email" bson:"contact_email"`
	ContactPhoneNumber string    `json:"contact_phone_number" bson:"contact_phone_number"`
}

type MultiBuildingEvents struct {
	Date      string                  `json:"date" bson:"date"`
	Buildings []*SingleBuildingEvents `json:"buildings" bson:"buildings"`
}

type Query struct {
}

type Room struct {
	Room     string `json:"room" bson:"room"`
	Capacity int32  `json:"capacity" bson:"capacity"`
}

type RoomEvents struct {
	Room   string             `json:"room" bson:"room"`
	Events []*SectionWithTime `json:"events" bson:"events"`
}

type SectionWithTime struct {
	Section   string `json:"section" bson:"section"`
	StartTime string `json:"start_time" bson:"start_time"`
	EndTime   string `json:"end_time" bson:"end_time"`
}

type SingleBuildingEvents struct {
	Building string        `json:"building" bson:"building"`
	Rooms    []*RoomEvents `json:"rooms" bson:"rooms"`
}
