package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"errors"
	"fmt"
	"graphql/graph/model"
	"strings"
	"time"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/mongo"
)

// AstraEvents is the resolver for the AstraEvents field.
func (r *queryResolver) AstraEvents(ctx context.Context, date string) (*model.AstraDayEvents, error) {
	timeoutCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()

	var out model.AstraDayEvents
	err := r.AstraCollection.FindOne(timeoutCtx, bson.M{"date": date}).Decode(&out)
	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) {
			return &model.AstraDayEvents{
				Date:      date,
				Buildings: []*model.AstraBuilding{},
			}, nil
		}
		return nil, err
	}
	if out.Buildings == nil {
		out.Buildings = []*model.AstraBuilding{}
	}
	return &out, nil
}

// AstraEventsByBuilding is the resolver for the AstraEventsByBuilding field.
func (r *queryResolver) AstraEventsByBuilding(ctx context.Context, date string, building string) (*model.AstraBuilding, error) {
	timeoutCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()

	building = strings.TrimSpace(building)

	var day model.AstraDayEvents
	err := r.AstraCollection.FindOne(timeoutCtx, bson.M{"date": date}).Decode(&day)
	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) {
			return nil, fmt.Errorf("no events found for the specified date")
		}
		return nil, err
	}

	var matched *model.AstraBuilding
	for i := range day.Buildings {
		b := day.Buildings[i]
		if b == nil {
			continue
		}
		if strings.EqualFold(strings.TrimSpace(b.Building), building) {
			matched = b
			break
		}
	}

	if matched == nil {
		maxBuildings := min(len(day.Buildings), 10)
		available := make([]string, 0, maxBuildings)
		for i := range maxBuildings {
			if day.Buildings[i] != nil {
				available = append(available, strings.TrimSpace(day.Buildings[i].Building))
			}
		}
		if len(day.Buildings) > maxBuildings {
			available = append(available, "(and more)")
		}
		return nil, fmt.Errorf("building not found. Available: %s", strings.Join(available, ", "))
	}

	return matched, nil
}

// AstraEventsByRoom is the resolver for the AstraEventsByRoom field.
func (r *queryResolver) AstraEventsByRoom(ctx context.Context, date string, building string, room string) (*model.AstraRoom, error) {
	timeoutCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()

	building = strings.TrimSpace(building)
	room = strings.TrimSpace(room)

	var day model.AstraDayEvents
	err := r.AstraCollection.FindOne(timeoutCtx, bson.M{"date": date}).Decode(&day)
	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) {
			return nil, fmt.Errorf("no events found for the specified date")
		}
		return nil, err
	}

	var matchedBuilding *model.AstraBuilding
	for i := range day.Buildings {
		b := day.Buildings[i]
		if b == nil {
			continue
		}
		if strings.EqualFold(strings.TrimSpace(b.Building), building) {
			matchedBuilding = b
			break
		}
	}

	if matchedBuilding == nil {
		return nil, fmt.Errorf("building not found")
	}

	var matchedRoom *model.AstraRoom
	for i := range matchedBuilding.Rooms {
		rr := matchedBuilding.Rooms[i]
		if rr == nil {
			continue
		}
		if strings.EqualFold(strings.TrimSpace(rr.Room), room) {
			matchedRoom = rr
			break
		}
	}

	if matchedRoom == nil {
		maxRooms := min(len(matchedBuilding.Rooms), 20)
		available := make([]string, 0, maxRooms)
		for i := range maxRooms {
			if matchedBuilding.Rooms[i] != nil {
				available = append(available, strings.TrimSpace(matchedBuilding.Rooms[i].Room))
			}
		}
		if len(matchedBuilding.Rooms) > maxRooms {
			available = append(available, "(and more)")
		}
		return nil, fmt.Errorf("room not found. Available in this building: %s", strings.Join(available, ", "))
	}

	return matchedRoom, nil
}
