package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"graphql/configs"
	"graphql/graph/model"
	"time"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo/options"
)

// AcademicCalendars is the resolver for the academicCalendars field.
func (r *queryResolver) AcademicCalendars(ctx context.Context, filter *model.AcademicCalendarFilter, offset *int32) ([]*model.AcademicCalendar, error) {
	timeoutCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()

	// Build query from filter
	var query bson.M
	if filter != nil {
		bsonBytes, err := bson.Marshal(filter)
		if err != nil {
			return nil, err
		}
		if err = bson.Unmarshal(bsonBytes, &query); err != nil {
			return nil, err
		}
	}

	// Pagination with sorting by id
	skip := int64(0)
	if offset != nil {
		skip = int64(*offset)
	}

	limit := configs.GetEnvLimit()
	paginate := options.Find().SetSkip(skip).SetLimit(limit).SetSort(bson.M{"_id": 1})

	// Query the correct collection
	cursor, err := r.AcademicCalendarCollection.Find(timeoutCtx, query, paginate)
	if err != nil {
		return nil, err
	}
	defer cursor.Close(timeoutCtx)

	var dbCalendars []*model.DBAcademicCalendar
	if err = cursor.All(timeoutCtx, &dbCalendars); err != nil {
		return nil, err
	}

	// Transform to GraphQL type
	calendars := make([]*model.AcademicCalendar, 0, len(dbCalendars))
	for _, dbCal := range dbCalendars {
		calendars = append(calendars, model.TransformCalendar(dbCal))
	}

	return calendars, nil
}

// AcademicCalendar is the resolver for the academicCalendar field.
func (r *queryResolver) AcademicCalendar(ctx context.Context, id string) (*model.AcademicCalendar, error) {
	timeoutCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()

	objectID, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, err
	}

	var dbCalendar model.DBAcademicCalendar
	err = r.AcademicCalendarCollection.FindOne(timeoutCtx, bson.M{"_id": objectID}).Decode(&dbCalendar)
	if err != nil {
		return nil, err
	}

	return model.TransformCalendar(&dbCalendar), nil
}
