package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"fmt"
	"graphql/configs"
	"graphql/graph/model"
	"log"
	"time"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
)

// CometCalendars is the resolver for the CometCalendars field.
func (r *queryResolver) CometCalendars(ctx context.Context, filter *model.CometCalendarFilter, offset *int32) ([]*model.CometCalendar, error) {
	timeoutCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()

	// Build query from filter
	var query bson.M
	if filter != nil {
		bsonBytes, err := bson.Marshal(filter)
		if err != nil {
			return nil, err
		}
		if err = bson.Unmarshal(bsonBytes, &query); err != nil {
			return nil, err
		}
	}

	// Pagination with sorting by id
	skip := int64(0)
	if offset != nil {
		skip = int64(*offset)
	}

	limit := configs.GetEnvLimit()
	paginate := options.Find().SetSkip(skip).SetLimit(limit).SetSort(bson.M{"_id": 1})

	// Query the correct collection
	cursor, err := r.CometCalendarCollection.Find(timeoutCtx, query, paginate)
	if err != nil {
		return nil, err
	}
	defer cursor.Close(timeoutCtx)

	var dbCalendars []*model.DBCometCalendar
	if err = cursor.All(timeoutCtx, &dbCalendars); err != nil {
		return nil, err
	}

	// Transform to GraphQL type
	calendars := make([]*model.CometCalendar, 0, len(dbCalendars))
	for _, dbCal := range dbCalendars {
		calendars = append(calendars, model.TransformCalendar(dbCal))
	}

	return calendars, nil
}

// CometCalendar is the resolver for the CometCalendar field.
func (r *queryResolver) CometCalendar(ctx context.Context, id string) (*model.CometCalendar, error) {
	timeoutCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()

	count, _ := r.CometCalendarCollection.CountDocuments(timeoutCtx, bson.M{})
	log.Printf("In Function:\tCometCalendar count: %d", count)

	objectId, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, err
	}

	var dbCalendar model.DBCometCalendar
	err = r.CometCalendarCollection.FindOne(timeoutCtx, bson.M{"_id": objectId}).Decode(&dbCalendar)
	if err != nil {
		if err == mongo.ErrNoDocuments {
			return nil, fmt.Errorf("calendar not found: cannot find collection")
		}
		return nil, err
	}

	return model.TransformCalendar(&dbCalendar), nil
}
