package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"errors"
	"fmt"
	"graphql/configs"
	"graphql/graph/model"
	"time"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
)

// CometCalendars is the resolver for the CometCalendars field.
// CometCalendars is the resolver for the CometCalendars field.
func (r *queryResolver) CometCalendars(ctx context.Context, filter *model.CometCalendarFilter, offset *int32) ([]*model.CometCalendar, error) {
	timeoutCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()

	// Build query from filter explicitly. JSON will not work due to nested type conflicts
	query := buildCometCalendarQuery(filter)

	// Pagination
	skip := int64(0)
	if offset != nil {
		skip = int64(*offset)
	}

	limit := configs.GetEnvLimit()
	paginate := options.Find().SetSkip(skip).SetLimit(limit)

	// Query the correct collection
	cursor, err := r.CometCalendarCollection.Find(timeoutCtx, query, paginate)
	if err != nil {
		return nil, err
	}
	defer cursor.Close(timeoutCtx)

	var calendars []*model.CometCalendar
	if err = cursor.All(timeoutCtx, &calendars); err != nil {
		return nil, err
	}

	/* Filter nested buildings array */
	if filter != nil && len(filter.Buildings) > 0 {
		// Collect requested building names
		buildingNames := []string{}
		for _, b := range filter.Buildings {
			if b != nil && b.Building != nil {
				buildingNames = append(buildingNames, *b.Building)
			}
		}
		// If there are building with that requested building name, filter buildings in calendar accordingly
		if len(buildingNames) > 0 {
			for _, cal := range calendars {
				filteredBuildings := []*model.CometCalendarBuilding{}
				for _, bldg := range cal.Buildings {
					for _, name := range buildingNames {
						if bldg.Building == name {
							filteredBuildings = append(filteredBuildings, bldg)
							break
						}
					}
				}
				cal.Buildings = filteredBuildings
			}
		}
	}

	return calendars, nil
}

// CometCalendar is the resolver for the CometCalendar field.
func (r *queryResolver) CometCalendar(ctx context.Context, id string) (*model.CometCalendar, error) {
	timeoutCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()

	objectId, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, err
	}

	var calendar model.CometCalendar
	err = r.CometCalendarCollection.FindOne(timeoutCtx, bson.M{"_id": objectId}).Decode(&calendar)
	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) {
			return nil, fmt.Errorf("calendar not found: cannot find collection")
		}
		return nil, err
	}

	return &calendar, nil
}

// buildCometCalendarQuery constructs a MongoDB query from the filter,
// handling buildings and rooms manually to avoid issues converting nested GraphQL filters to BSON.
func buildCometCalendarQuery(filter *model.CometCalendarFilter) bson.M {
	query := bson.M{}

	if filter != nil {
		if filter.Date != nil {
			query["date"] = *filter.Date
		}

		if len(filter.Buildings) > 0 {
			var buildingNames []string
			var roomNames []string

			for _, b := range filter.Buildings {
				// Collect building names
				if b != nil && b.Building != nil {
					buildingNames = append(buildingNames, *b.Building)
				}

				// Collect room names inside each building
				if b != nil && b.Rooms != nil {
					for _, r := range b.Rooms {
						if r != nil && r.Room != nil {
							roomNames = append(roomNames, *r.Room)
						}
					}
				}
			}

			// Filter by room(s) if any
			if len(roomNames) > 0 {
				query["buildings.rooms.room"] = bson.M{"$in": roomNames}
			}
			if len(buildingNames) > 0 {
				query["buildings.building"] = bson.M{"$in": buildingNames}
			}
		}
	}

	return query
}
