package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"errors"
	"graphql/graph/model"
	"time"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/mongo"
)

// MazevoEvents is the resolver for the MazevoEvents field.
func (r *queryResolver) MazevoEvents(ctx context.Context, date string) (*model.MazevoDayEvents, error) {
	timeoutCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()

	var out model.MazevoDayEvents
	err := r.MazevoCollection.FindOne(timeoutCtx, bson.M{"date": date}).Decode(&out)
	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) {
			return &model.MazevoDayEvents{
				Date:      date,
				Buildings: []*model.MazevoBuilding{},
			}, nil
		}
		return nil, err
	}
	if out.Buildings == nil {
		out.Buildings = []*model.MazevoBuilding{}
	}
	return &out, nil
}
