package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.27

import (
	"context"

	"github.com/LocatingWizard/nebula_api_graphql/graph/model"
)

// Sections is the resolver for the sections field.
func (r *professorResolver) Sections(ctx context.Context, obj *model.Professor) ([]*model.Section, error) {
	var out []*model.Section
	section_ids := obj.Sections
	for _, id := range section_ids {
		section, err := r.Query().SectionByID(ctx, id.Hex())
		if err != nil {
			return nil, err
		}
		out = append(out, section)
	}
	return out, nil
}

// Professor returns ProfessorResolver implementation.
func (r *Resolver) Professor() ProfessorResolver { return &professorResolver{r} }

type professorResolver struct{ *Resolver }
