package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"graphql/graph/model"
	"time"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo/options"
)

// Courses is the resolver for the courses field.
func (r *queryResolver) Courses(ctx context.Context, filter *model.CourseFilter, limit *int32, offset *int32) ([]*model.Course, error) {
	timeoutCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()

	var courses []*model.Course     // Courses on GraphQL side
	var dbCourses []*model.DBCourse // Courses on Mongo side
	var err error

	// Build the mongo query from the filter's struct
	var courseQuery bson.M
	bsonBytes, err := bson.Marshal(filter)
	if err != nil {
		return nil, err
	}
	if err = bson.Unmarshal(bsonBytes, &courseQuery); err != nil {
		return nil, err
	}
	// Paginate the list of courses
	paginate := options.Find().SetSkip(int64(*offset)).SetLimit(int64(*limit))

	// Query from Database
	cursor, err := r.CourseCollection.Find(timeoutCtx, courseQuery, paginate)
	if err != nil {
		return nil, err
	}
	defer cursor.Close(timeoutCtx)

	// Parse the cursor from database to the course types
	if err = cursor.All(timeoutCtx, &dbCourses); err != nil {
		return nil, err
	}

	// Transform Mongo course to GraphQL course
	for _, dbCourse := range dbCourses {
		courses = append(courses, model.TransformCourse(dbCourse))
	}

	return courses, err
}

// Course is the resolver for the course field.
func (r *queryResolver) Course(ctx context.Context, id string) (*model.Course, error) {
	timeoutCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()

	var dbCourse *model.DBCourse
	var err error

	objectId, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, err
	}

	err = r.CourseCollection.FindOne(
		timeoutCtx, bson.M{"_id": objectId}).Decode(dbCourse)
	if err != nil {
		return nil, err
	}

	return model.TransformCourse(dbCourse), err
}

// Rooms is the resolver for the rooms field.
func (r *queryResolver) Rooms(ctx context.Context) ([]*model.BuildingRooms, error) {
	timeoutCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()

	var buildingRooms []*model.BuildingRooms
	var err error

	cursor, err := r.BuildingCollection.Find(timeoutCtx, bson.M{})
	if err != nil {
		return buildingRooms, err
	}
	defer cursor.Close(timeoutCtx)

	if err = cursor.All(ctx, &buildingRooms); err != nil {
		return buildingRooms, err
	}

	return buildingRooms, err
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
