package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// RoomEvents returns RoomEventsResolver implementation.
func (r *Resolver) RoomEvents() RoomEventsResolver { return &roomEventsResolver{r} }

// SingleBuildingEvents returns SingleBuildingEventsResolver implementation.
func (r *Resolver) SingleBuildingEvents() SingleBuildingEventsResolver {
	return &singleBuildingEventsResolver{r}
}

// MultiBuildingEvents returns MultiBuildingEventsResolver implementation.
func (r *Resolver) MultiBuildingEvents() MultiBuildingEventsResolver {
	return &multiBuildingEventsResolver{r}
}

type queryResolver struct{ *Resolver }
type roomEventsResolver struct{ *Resolver }
type singleBuildingEventsResolver struct{ *Resolver }
type multiBuildingEventsResolver struct{ *Resolver }
