package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations will be copied through when generating and any unknown code will
// be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"graphql/configs"
	"graphql/graph/model"
	"time"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo/options"
)

// section is the resolver here
func (r *queryResolver) Sections(
	ctx context.Context,
	filter *modelSectionFilter, 
	offset *int32, 
) ([]*model.Section, error) {
	timeoutCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()

	//graphql output
	var sections []*model.Section

	// mongo decoding target
	var dbSections []*model.DBSection

	// yet to build mongo query filter

}
