steps:
  - name: gcr.io/cloud-builders/docker
    id: Build
    args:
      - build
      - --no-cache
      - -t
      - $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$_SERVICE_NAME:$COMMIT_SHA
      - -f
      - rest/Dockerfile
      - .

  - name: gcr.io/cloud-builders/docker
    id: Push
    args:
      - push
      - $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$_SERVICE_NAME:$COMMIT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: Deploy
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - --platform=managed
      - --image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$_SERVICE_NAME:$COMMIT_SHA
      - --labels=commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID
      - --region=$_DEPLOY_REGION
      - --quiet

images:
  - $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$_SERVICE_NAME:$COMMIT_SHA

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _DEPLOY_REGION: us-south1
  _AR_HOSTNAME: us-south1-docker.pkg.dev
  _SERVICE_NAME: dev-nebula-api

tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - dev-nebula-api
