# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "graphql-v2" ]
  pull_request:
    branches: [ "graphql-v2" ]
  workflow_dispatch:

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      graphql: ${{ steps.filter.outputs.graphql }}
      rest: ${{ steps.filter.outputs.rest }}
      shared: ${{ steps.filter.outputs.shared }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Detect paths of changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            graphql:
              - 'graphql/**'
            rest:
              - 'rest/**'
              - 'update-gateway.sh'
              - 'update-gateway.bat'
            shared:
              - 'shared/**'

  build_ubuntu:
    name: Build Ubuntu
    needs: detect_changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'
          cache-dependency-path: "**/go.sum"

      - name: Setup
        run: make setup

      - name: Check
        run: make check

      - name: Test
        shell: bash
        run: |
          log_test() { echo -e "\033[34m$1\033[0m" }
          log_warn() { echo -e "\033[33m$1\033[0m" }

          if [[ "${{ needs.detect_changes.outputs.rest }}" = "true" ]]; then
            log_test "Unit test the REST server"
            make test-rest
          elif [[ "${{ needs.detect_changes.outputs.graphql }}" = "true" ]]; then
            log_test "Unit test the GraphQL server"
            make test-graphql
          elif [[ "${{ needs.detect_changes.outputs.shared }}" = "true" ]]; then
            log_test "Unit test the shared module"
            make test-shared
          else
            log_warn "Nothing to test"
          fi
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}

      - name: Builds
        shell: bash
        run: |
          log_build() { echo -e "\033[35m$1\033[0m" }

          # If changes are in rest, then build rest
          # If changes are in graphql, then build graphql
          # If changes are in any other parts, then build both servers
          if [[ "${{ needs.detect_changes.outputs.rest }}" = "true" ]]; then
            log_build "Build-test the REST server"
            make build-rest
          elif [[ "${{ needs.detect_changes.outputs.graphql }}" = "true" ]]; then
            log_build "Build-test the GraphQL server"
            make build-graph
          else
            log_build "Build-test REST and GraphQL server"
            make build
          fi

  build_windows:
    name: Build Windows
    needs: detect_changes
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'
          cache-dependency-path: "**\\go.sum"

      - name: Setup
        run: .\build.bat setup

      - name: Check
        run: .\build.bat checks

      - name: Test
        shell: pwsh
        run: |
          function Write-TestLog {
            param(
              [string]$Message
            )
            Write-Host $Message -ForegroundColor Cyan
          }

          function Write-WarnLog {
            param(
              [string]$Message
            )
            Write-Host $Message -ForegroundColor Yellow
          }

          # Depending on changes are in Rest or Graphql server, only test that server
          if ("${{ needs.detect_changes.outputs.rest }}" -eq "true") {
            Write-TestLog "Unit test the REST server"
            .\build.bat test-rest
          }
          elseif ("${{ needs.detect_changes.outputs.graphql }}" -eq "true") {
            Write-TestLog "Unit test the GraphQL server"
            .\build.bat test-graphql
          }
          elseif ("${{ needs.detect_changes.outputs.shared }}" -eq "true") {
            Write-TestLog "Unit test the shared module"
            .\build.bat test-shared
          }
          else {
            Write-WarnLog "Nothing to test"
          }
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}

      - name: Builds
        shell: pwsh
        run: |
          function Write-BuildLog {
            param(
              [string]$Message
            )
            Write-Host $Message -ForegroundColor Magenta
          }

          if ("${{ needs.detect_changes.outputs.rest }}" -eq "true") {
            Write-BuildLog "Build-test the REST server"
            .\build.bat build-rest
          }
          elseif ("${{ needs.detect_changes.outputs.graphql }}" -eq "true") {
            Write-BuildLog "Build-test the GraphQL server"
            .\build.bat build-graph
          }
          else {
            Write-BuildLog "Build-test REST and GraphQL server"
            .\build.bat build
          }
